### ISSUE TITLE
要不要加入全家桶？

### ISSUE THREAD

**Issue by david082321** [frowhy/Wake#3]
QAQ
不晓得schema是什么？我原本还以为是网址列(＞﹏＜) 
现在才发现我好像错了Σ( ° △ °|||)︴

**Comment by frowhy** [comment]
这东西肯定是越多越好的...

**Comment by frowhy** [comment]
话说,这么看来你是不闪退的?事实上通过as debug的话是不会闪退的,我也不知道为什么发布release就会闪退...我找找原因...

**Comment by david082321** [comment]
酷安
coolapk

三星商城
samsungapps
apps.samsung

Onedrive
1drv.ms
onedrive.live

MEGA
mega.co
mega.nz

Facebook
fb.com
facebook

**Comment by david082321** [comment]
地圖
maps.google
local.google
mapy.google

Play
play.google
market.android

YouTube
youtube
youtu.be

翻譯
translate.google

地球
earth.google

相簿
photos.google

雲端硬碟
docs.google
drive.google
spreadsheets.google

Hangouts
hangouts.google
g.co

Play音樂
music.google

**Comment by david082321** [comment]
能不能每个都做一个开关，有些时候并不想要启动冻结的应用，又不想卸载应用。

例如：使用Facebook(以下简称fb)绑定游戏时，如果fb尚未冻结，就会调用fb登录的帐号；如果fb已被冻结，就会开启网页版自行登录。
今天如果我想用小号登录这个游戏，不就只能卸载fb(大号已经登录了)或是重新在fb登录小号，然后才能用小号登录游戏

**Comment by frowhy** [comment]
你把issue关了,我看不到了...

**Comment by frowhy** [comment]
开关功能已经加了,不过是全局的.

**Comment by david082321** [comment]
帮忙加一下吧，电脑坏了，只能用手机打字QAQ
//Google全家桶
fireball
com.google.android.apps.fireball

otpauth
com.google.android.apps.authenticator2

gplus
com.google.android.apps.plus

assistant-handoff，assistant-settings，app，android-app
com.google.android.googlequicksearchbox

inboxapp
com.google.android.apps.inbox

gmail2from，feedback
com.google.android.gm

googleplaymusic
com.google.android.music

vnd.youtube，vnd.youtube.launch
com.google.android.youtube

google.maps.taxi，googlemapstaxi，peterparker，geo.replay，google.navigation，google.maps，google.streetview，google.maps.timeline
com.google.android.apps.maps

geo
com.google.earth，com.google.android.apps.maps

googletranslate
com.google.android.apps.translate
