### ISSUE TITLE
一堆规则求加

### ISSUE THREAD

**Issue by david082321** [frowhy/Wake#7]
//start Facebook全家桶
facebook，fb，fblogin，fbinternal，fb-register
com.facebook.katana

fblite，dialtone
com.facebook.lite

fb-messenger，fb-messenger-secure，fb-messenger-sametask
com.facebook.orca
//end Facebook全家桶

//MEGA
mega
mega.privacy.android.app

//有妖气
u17comic
com.u17.comic.phone

//Whoscall
whoscallio，whoscall
gogolook.callgogolook2

//起点
qdreader，QDreader，tencentcom.qidian.QDReader，qwalletcom.qidian.QDReader
com.qidian.QDReader

//网易云音乐
orpheus，orpheus-cortana
com.netease.cloudmusic

//欢乐书客
hbooker
com.kuangxiang.novel

**Comment by david082321** [comment]
从jingdong到baiduyun的包名错了吧?
下面的geo也错了

怎么会开启qq空间(com.qzone)呢

**Comment by frowhy** [comment]
错误的包名已经改掉了...其他的要加你自己加吧,,,我眼睛已经花了...
